### ISSUE TITLE
Mobile Device: Door Galleries 

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#21]
On mobile, there's an extra menu to select the type of door gallery (Entry Door, Patio, Storm) that is unnecessary and confusing on mobile because when you select one of those, it just takes you to the top of the main gallery page and not to a specific gallery for that door type.  Suggest getting rid of those menu items in mobile and just have people navigate down the main Door Gallery page to the buttons for the door type they want to see.

![image](https://user-images.githubusercontent.com/78490468/159139671-18f4ed3e-96a5-4673-a3ae-78d90773fa05.png)

**Comment by SeanIsAtWork** [comment]
This has been fixed, there is no further menu upon clicking door gallery and instead takes you to the door gallery page. Same goes for window gallery

**Comment by PilotFish3447** [comment]
This is still an issue in the mobile menu - Entry Doors, Patio Doors and Storm Doors menus show up under Door Gallery nav link -- remove from mobile menu.
