### ISSUE TITLE
Grout Visualizer not working in iFrame

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#329]
When I click on the stone thumbnails in the grout visualizer on an iFrame page, nothing happens:
https://www.pilotfishseo.com/provia-grout-visualizer/

**Comment by ancaipen** [comment]
@PilotFish3447 - This bug has been fixed.  Pop-up is now working in the iframe.  CSS updates may need to be applied to move pop-up to placement where iframe can be seen better.  It is currently displayed in the center of the page.  Issue #323 is related to this issue.

**Comment by PilotFish3447** [comment]
Grout visualizer still not loading properly in iFrame when you click on an individual stone thumbnail -- still just displaying a grayed out content area:
https://www.pilotfishseo.com/provia-grout-visualizer/
https://www.pilotfishseo.com/provia-ridge-cut/ 
![image](https://user-images.githubusercontent.com/78490468/164470329-fee1da75-6bef-46c0-b584-9f3cc10fca78.png)

**Comment by PilotFish3447** [comment]
@ancaipen I checked this afternoon - this is still an issue.

**Comment by ancaipen** [comment]
@PilotFish3447 : I switched this to be a pop-up for iframe requests only.  Take a look at this and let me know if this functions better. 

![image](https://user-images.githubusercontent.com/43222107/167465975-0b40ae2a-4712-4bb9-8258-603e9ed708ec.png)

**Comment by PilotFish3447** [comment]
@ancaThis is a good solution.  Works well. I'm closing it out.
