### ISSUE TITLE
Re-load issue with Endure window 3D animation

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#330]
In testing the responsive sizes, the Endure window 3D animation was kinda buggy, kept re-loading the page and then caused an error.  Happened on multiple browsers and sizes.
https://www.pilotfishseo.com/provia-endure/

**Comment by plaugs** [comment]
Can you provide any more details? I can't duplicate the issue. Maybe a screenshot or video?

**Comment by PilotFish3447** [comment]
@plaugs - I don't know how to videotape the issue, but on the iPhone, the animation keeps reloading, then generates an error that says "A problem repeatedly occurred on https://provia.proviaserver-v2.com/windows/brands/endure/." On the iPad, once the animation loads, it shakes non-stop, so I think it's re-loading there too.

**Comment by plaugs** [comment]
Ok clear your cache and check it again. There was a style that was not applied to that column for some reason.

**Comment by PilotFish3447** [comment]
@plaugs I re-checked both on iPhone on Browserstack and my personal iPhone. On Browserstack, the image shakes uncontrollably. On my iPhone, it re-loads a few times and then generates an error message that says: "A problem repeatedly occurred on https://provia.proviaserver-v2.com/windows/brands/endure/." I re-checked the other brand pages and the same issue occurs on Aspect window page, but not on Aeris or ecoLite.

**Comment by PilotFish3447** [comment]
@plaugs This is still an issue for both the Endure and Aspect window pages on iPhone.  I checked it on my personal iPhone and on Browserstack iPhone and iPad. Still an issue.

**Comment by plaugs** [comment]
@SeanIsAtWork can you verify this with browser stack or let me use the log-in? I am not sure how to duplicate this issue.

**Comment by plaugs** [comment]
Ok I found out there was a css glitch in safari. Problem should be fixed.

**Comment by SeanIsAtWork** [comment]
@plaugs This isnt working for me still, I'm using brave browser (chromium) on my phone (iphone SE). But im noticing that the endure page takes at least 30 seconds sometimes to load the 3d model, aspect around 20 seconds or so. Compare that to the Aeris and Ecolite which are around 10-12 seconds at most with ecolite being the fastest to load (around 8 seconds). 

Could there be duplicate/complex/unnecessary elements on the model that could be adding to the load time/reloading/glitching out going on?

**Comment by PilotFish3447** [comment]
@plaugs I re-tested on my iPhone also - still not loading properly.

**Comment by PilotFish3447** [comment]
@plaugs I only saw this happening on the Endure and Aspect window pages.

**Comment by plaugs** [comment]
Issue should be fixed now.

**Comment by PilotFish3447** [comment]
YES!  Both load great.  And, it actually seems like the pages load faster now too.  I'm closing this out.
